apps/user/urls.py
# apps/user/urls.py

# Django modules
from django.urls import path

# Locals
from apps.user import views 

app_name = 'user'

urlpatterns = [

    # Login template
    path('', views.user_login, name='user_login'),
    # User login
    path('doLogin/', views.doLogin, name='doLogin'),
    # User logout
    path('doLogout/', views.doLogout, name='doLogout'),
    # User profile
    path('profile/', views.profile, name='profile'),
    # User profile
    path('profile/update/', views.profile_update, name='profile_update'),
]

config/urls.py
# config/urls.py

# Django modules
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # user
    path('', include('apps.user.urls', namespace='user')),

    # hod
    path('', include('apps.hod.urls', namespace='hod')),


    # student
    path('', include('apps.student.urls', namespace='student')),


    # main
    path('', include('apps.main.urls', namespace='main')),

    # Admin
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/user/models.py
# apps/user/models.py

# Django modules
from django.db import models
from django.contrib.auth.models import AbstractUser  

# Locals

# Create your models here.

class CustomUserModel(AbstractUser):

	USER = (
		(1, 'Hod'),
		(2, 'Staff'),
		(3, 'Student'),
	)

	user_type = models.CharField(choices=USER,max_length=50,default=1)
	profile_pic = models.ImageField(upload_to='images/profile_pic')

apps/user/views.py
# apps/user/views.py

# Django modules
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth import authenticate, logout, login
from django.contrib import messages
from django.contrib.auth.decorators import login_required

# Locals
from apps.user.EmailBackEnd import EmailBackEnd 
from apps.user.models import CustomUserModel

# Create your views here.

# Login template
def user_login(request):
	return render(request, 'user/login.html')


# User login
def doLogin(request):

	if request.method == 'POST':
		user = EmailBackEnd.authenticate(request,
										 username=request.POST.get('email'),
										 password=request.POST.get('password'))

		if user != None:
			login(request,user)
			user_type = user.user_type

			if user_type == '1':
				# return HttpResponse('This is HOD Panel')
				return redirect('hod:hod_home')

			elif user_type == '2':
				return HttpResponse('This is Staff Panel')

			elif user_type == '3':
				return HttpResponse('This is Student Panel')

			else:
				# message
				messages.error(request, 'Invalid email or password!')
				return redirect('user:user_login') 

		else:
			# message
			messages.error(request, 'Invalid email or password!')
			return redirect('user:user_login')


# User logout
def doLogout(request):
	logout(request)
	return redirect('user:user_login')


# User profile
@login_required(login_url='user:user_login')
def profile(request):

	user = CustomUserModel.objects.get(id=request.user.id)

	# print(user)
	
	context = {'user':user}
	return render(request, 'user/profile.html', context)


# User profile update
@login_required(login_url='user:user_login')
def profile_update(request):

	if request.method == 'POST':
		profile_pic = request.FILES.get('profile_pic')
		first_name  = request.POST.get('first_name')
		last_name   = request.POST.get('last_name')
		# email  		= request.POST.get('email')
		# username  	= request.POST.get('username')
		password  	= request.POST.get('password')

		# testing
		print(profile_pic)
		# print(first_name, last_name, password)
		# print(profile_pic, first_name, last_name, email, username, password)

		try:
			customuser = CustomUserModel.objects.get(id=request.user.id)

			customuser.first_name 	= first_name
			customuser.last_name 	= last_name
			# customuser.username 	= username
			# customuser.profile_pic 	= profile_pic
			
			if password != None and password != "":
				customuser.set_password(password)

			if profile_pic != None and profile_pic != "":
				customuser.profile_pic = profile_pic

			customuser.save()

			messages.success(request, 'Profile updated successfully!')
			# redirect('user:profile_update')
			# return redirect('hod:hod_home')
			return redirect('user:profile')
			# return redirect('user:profile_update')

		except:
			messages.error(request, 'Failed to update Profile!')

	context = {}
	return render(request, 'user/profile.html', context)

apps/user/templates/user/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Login {% endblock title %}

{% block content %}

<!DOCTYPE html>
<html lang="en">
<!-- Mirrored from preschool.dreamguystech.com/html-template/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Oct 2021 11:11:39 GMT -->
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0" />
    <title>Preskool - Login</title>
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.png' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,500;0,600;0,700;1,400&amp;display=swap" />
    <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/fontawesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />
</head>
<body>
    <div class="main-wrapper login-body">
        <div class="login-wrapper">
            <div class="container">
                <div class="loginbox">
                    <div class="login-left">
                        <img class="img-fluid" src="{% static 'assets/img/logo-white.png' %}" alt="Logo" />
                    </div>
                    <div class="login-right">
                        <div class="login-right-wrap">

                            <!-- Header -->
                            <h1>Login</h1>
                            <p class="account-subtitle">Access to our dashboard</p>
                            <!-- Header end -->

                            <!-- Falsh Message -->
                            {% if messages %}
                            {% for message in messages %}
                            {% if message.tags == 'error' %}
                            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                              <strong>Holy guacamole!</strong>{{message}}
                              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                              </button>
                            </div>
                            {% endif %}
                            {% endfor %}
                            {% endif %}
                            <!-- Flash message end -->

                            <form 
                                action="{% url 'user:doLogin' %}" 
                                method="POST">

                                {% csrf_token %}
                                
                                <div class="form-group">
                                    <input
                                        name='email' 
                                        class="form-control" 
                                        type="text" 
                                        placeholder="Email" />
                                </div>

                                <div class="form-group">
                                    <input
                                        name='password' 
                                        class="form-control" 
                                        type="password" 
                                        placeholder="Password" />
                                </div>

                                <div class="form-group">
                                    <button 
                                        class="btn btn-primary btn-block" 
                                        type="submit">Login</button>
                                </div>

                            </form>
                            <div class="text-center dont-have">Don’t have an account? <a href="register.html">Register</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'ssets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>
</body>
<!-- Mirrored from preschool.dreamguystech.com/html-template/login.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 28 Oct 2021 11:11:40 GMT -->
</html>


{% endblock content %}

apps/user/templates/user/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profile {% endblock title %}

{% block content %}

   
        <div class="content container-fluid">
<!--             <div class="page-header">
                <div class="row align-items-center">
                    <div class="col">
                        <h3 class="page-title">Profile</h3>
                        <ul class="breadcrumb">
                            <li class="breadcrumb-item"><a href="subjects.html">Subject</a></li>
                            <li class="breadcrumb-item active">Profile Update</li>
                        </ul>
                    </div>
                </div>
            </div> -->

            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <form 
                                method="POST" 
                                action="{% url 'user:profile_update' %}"
                                enctype="multipart/form-data">

                                {% csrf_token %}

                                <div class="col-sm-12">
                                    <h5 class="form-title"><span>Profile Update</span></h5>
                                </div>

                                <!-- Falsh Message -->
                                {% if messages %}
                                {% for message in messages %}
                                {% if message.tags == 'error' %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                  <strong>Holy guacamole!</strong>{{message}}
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                <!-- Flash message end -->

                                <!-- Falsh Message -->
                                {% if messages %}
                                {% for message in messages %}
                                {% if message.tags == 'success' %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                  <strong>Holy guacamole!</strong>{{message}}
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                <!-- Flash message end -->

                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Profile Pic</label>
                                        <input 
                                            type="file" 
                                            name="profile_pic" 
                                            class="form-control" />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>First Name</label>
                                        <input 
                                            type="text" 
                                            name="first_name" 
                                            class="form-control"
                                            placeholder="Enter first name" />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Last Name</label>
                                        <input 
                                            type="text" 
                                            name="last_name" 
                                            class="form-control" 
                                            placeholder="Enter last name" />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input 
                                            type="text" 
                                            name="email" 
                                            class="form-control" 
                                            placeholder="Enter email"
                                            readonly />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input 
                                            type="text" 
                                            name="username" 
                                            class="form-control" 
                                            placeholder="Enter username"
                                            readonly />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input 
                                            type="password" 
                                            name="password" 
                                            class="form-control" 
                                            placeholder="Fill only if you want to change your password" 
                                            />
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button 
                                        type="submit"
                                        class="btn btn-primary">Update profile</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>


{% endblock content %}

apps/user/templates/user/profileXX.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Profile {% endblock title %}

{% block content %}


         <div class="page-wrapper">
             <div class="content container-fluid">
                 <div class="page-header">
                     <div class="row">
                         <div class="col">
                             <h3 class="page-title">Profile</h3>
                             <ul class="breadcrumb">
                                 <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                                 <li class="breadcrumb-item active">Profile</li>
                             </ul>
                         </div>
                     </div>
                 </div>
                 <div class="row">
                     <div class="col-md-12">
                         <div class="profile-header">
                             <div class="row align-items-center">
                                 <div class="col-auto profile-image">
                                     <a href="#">
                                         <img class="rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-02.jpg' %}" />
                                     </a>
                                 </div>
                                 <div class="col ml-md-n2 profile-user-info">
                                     <h4 class="user-name mb-0">John Doe</h4>
                                     <h6 class="text-muted">UI/UX Design Team</h6>
                                     <div class="user-Location"><i class="fas fa-map-marker-alt"></i> Florida, United States</div>
                                     <div class="about-text">Lorem ipsum dolor sit amet.</div>
                                 </div>
                                 <div class="col-auto profile-btn">
                                     <a href="#" class="btn btn-primary">
                                         Edit
                                     </a>
                                 </div>
                             </div>
                         </div>
                         <div class="profile-menu">
                             <ul class="nav nav-tabs nav-tabs-solid">
                                 <li class="nav-item">
                                     <a class="nav-link active" data-toggle="tab" href="#per_details_tab">About</a>
                                 </li>
                                 <li class="nav-item">
                                     <a class="nav-link" data-toggle="tab" href="#password_tab">Password</a>
                                 </li>
                             </ul>
                         </div>
                         <div class="tab-content profile-tab-cont">
                             <div class="tab-pane fade show active" id="per_details_tab">
                                 <div class="row">
                                     <div class="col-lg-9">
                                         <div class="card">
                                             <div class="card-body">
                                                 <h5 class="card-title d-flex justify-content-between">
                                                     <span>Personal Details</span>
                                                     <a class="edit-link" data-toggle="modal" href="#edit_personal_details"><i class="far fa-edit mr-1"></i>Edit</a>
                                                 </h5>
                                                 <div class="row">
                                                     <p class="col-sm-3 text-muted text-sm-right mb-0 mb-sm-3">Name</p>
                                                     <p class="col-sm-9">John Doe</p>
                                                 </div>
                                                 <div class="row">
                                                     <p class="col-sm-3 text-muted text-sm-right mb-0 mb-sm-3">Date of Birth</p>
                                                     <p class="col-sm-9">24 Jul 1983</p>
                                                 </div>
                                                 <div class="row">
                                                     <p class="col-sm-3 text-muted text-sm-right mb-0 mb-sm-3">Email ID</p>
                                                     <p class="col-sm-9">
                                                         <a href="https://preschool.dreamguystech.com/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="711b1e191f151e14311409101c011d145f121e1c">[email&#160;protected]</a>
                                                     </p>
                                                 </div>
                                                 <div class="row">
                                                     <p class="col-sm-3 text-muted text-sm-right mb-0 mb-sm-3">Mobile</p>
                                                     <p class="col-sm-9">305-310-5857</p>
                                                 </div>
                                                 <div class="row">
                                                     <p class="col-sm-3 text-muted text-sm-right mb-0">Address</p>
                                                     <p class="col-sm-9 mb-0">
                                                         4663 Agriculture Lane,<br />
                                                         Miami,<br />
                                                         Florida - 33165,<br />
                                                         United States.
                                                     </p>
                                                 </div>
                                             </div>
                                         </div>
                                     </div>
                                     <div class="col-lg-3">
                                         <div class="card">
                                             <div class="card-body">
                                                 <h5 class="card-title d-flex justify-content-between">
                                                     <span>Account Status</span>
                                                     <a class="edit-link" href="#"><i class="far fa-edit mr-1"></i> Edit</a>
                                                 </h5>
                                                 <button class="btn btn-success" type="button"><i class="fe fe-check-verified"></i> Active</button>
                                             </div>
                                         </div>
                                         <div class="card">
                                             <div class="card-body">
                                                 <h5 class="card-title d-flex justify-content-between">
                                                     <span>Skills </span>
                                                     <a class="edit-link" href="#"><i class="far fa-edit mr-1"></i> Edit</a>
                                                 </h5>
                                                 <div class="skill-tags">
                                                     <span>Html5</span>
                                                     <span>CSS3</span>
                                                     <span>WordPress</span>
                                                     <span>Javascript</span>
                                                     <span>Android</span>
                                                     <span>iOS</span>
                                                     <span>Angular</span>
                                                     <span>PHP</span>
                                                 </div>
                                             </div>
                                         </div>
                                     </div>
                                 </div>
                             </div>
                             <div id="password_tab" class="tab-pane fade">
                                 <div class="card">
                                     <div class="card-body">
                                         <h5 class="card-title">Change Password</h5>
                                         <div class="row">
                                             <div class="col-md-10 col-lg-6">
                                                 <form>
                                                     <div class="form-group">
                                                         <label>Old Password</label>
                                                         <input type="password" class="form-control" />
                                                     </div>
                                                     <div class="form-group">
                                                         <label>New Password</label>
                                                         <input type="password" class="form-control" />
                                                     </div>
                                                     <div class="form-group">
                                                         <label>Confirm Password</label>
                                                         <input type="password" class="form-control" />
                                                     </div>
                                                     <button class="btn btn-primary" type="submit">Save Changes</button>
                                                 </form>
                                             </div>
                                         </div>
                                     </div>
                                 </div>
                             </div>
                         </div>
                     </div>
                 </div>
             </div>
         </div>

{% endblock content %}