apps/student/urls.py
# apps/student/urls.py

# Django modules
from django.urls import path

# Locals
from apps.student import views 

app_name = 'student'

urlpatterns = [

    path('student/add-student/', views.add_student, name='add_student'),
    path('student/list/', views.list_student, name='list_student'),
    path('student/edit/<str:id>/', views.edit_student, name='edit_student'),
    
]

config/urls.py
# config/urls.py

# Django modules
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # user
    path('', include('apps.user.urls', namespace='user')),

    # hod
    path('', include('apps.hod.urls', namespace='hod')),


    # student
    path('', include('apps.student.urls', namespace='student')),


    # main
    path('', include('apps.main.urls', namespace='main')),

    # Admin
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/student/models.py
# apps/student/models.py

# Django modules
from django.db import models

# Locals
from apps.user.models import CustomUserModel

# Create your models here.

class Course(models.Model):
	name = models.CharField(max_length=100)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.name 


class Session_Year(models.Model):
	session_start = models.CharField(max_length=100)
	session_end = models.CharField(max_length=100)

	class Meta:
		verbose_name_plural = 'Session year'


	def __str__(self):
		return self.session_start + " - " + self.session_end


class Student(models.Model):
	admin = models.OneToOneField(CustomUserModel, on_delete=models.CASCADE)
	address = models.TextField()
	gender = models.CharField(max_length=100)
	course_id = models.ForeignKey(Course, on_delete=models.DO_NOTHING)
	session_year_id = models.ForeignKey(Session_Year, on_delete=models.DO_NOTHING)
	created_at = models.DateTimeField(auto_now_add=True)
	updated_at = models.DateTimeField(auto_now=True)

	def __str__(self):
		return self.admin.first_name + " " + self.admin.last_name

apps/student/views.py
# apps/student/views.py

# Django modules
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Locals
from apps.student.models import Course, Session_Year
from apps.user.models import CustomUserModel
from apps.student.models import Student, Course, Session_Year  

# Create your views here.


# Add student ----------------------------------------------------
@login_required(login_url='user:user_login')
def add_student(request):

	# 1. First thing first: fetch the course and session_year
	courses = Course.objects.all()
	session_years = Session_Year.objects.all()

	# Testing
	# print(courses)
	# print(session_years)

	# 2. Add logic if there is request method of POST to process the form input
	if request.method == 'POST':
		profile_pic = request.FILES.get('profile_pic')
		first_name = request.POST.get('first_name')
		last_name = request.POST.get('last_name')
		gender = request.POST.get('gender')
		address = request.POST.get('address')
		course_id = request.POST.get('course_id')
		session_year_id = request.POST.get('session_year_id')
		email = request.POST.get('email')
		username = request.POST.get('username')
		password = request.POST.get('password')

		# Testing
		# print(profile_pic, first_name, last_name, gender, address, course_id, session_year_id, email, username, password)
		# result
		# contact01.PNG teststudent1 teststudent1 Female teststudent1 1 1 teststudent1@email.com teststudent1 teststudent1

		# 3. Check the existance of email and username in the db bc they are unique
		#    send messages if any of them is exists in the db
		
		# 3.1 Check existance of the email (email=unique)
		if CustomUserModel.objects.filter(email=email).exists():
			messages.warning(request, 'Email is already taken !')
			return redirect('student:add_student')

		# 3.1 Check existance of username (email=unique)
		if CustomUserModel.objects.filter(username=username).exists():
			messages.warning(request, 'Username is already in used !')
			return redirect('student:add_student')

		# 4. Process the request if email and username are not exists in the db
		else:
			user = CustomUserModel(
				profile_pic=profile_pic,
				first_name = first_name,
				last_name  = last_name,
				username   = username,
				email 	   = email,
				user_type  = 3,
			)
			user.set_password(password)
			user.save()

			# 5. Making TWO in ONE: Student as user and Student's choice for course and session_year
			course = Course.objects.get(id=course_id)
			session_year = Session_Year.objects.get(id=session_year_id)

			student = Student(
				admin = user,
				gender = gender,
				address = address,
				course_id = course,
				session_year_id = session_year
			)

			student.save()
			messages.success(request, user.first_name + " " + user.last_name + ' Added successfully!')
			# messages.success(request, 'Student added successfully!')
			return redirect('student:add_student')
			# 5. end Making TWO in ONE: Student as user and Student's choice for course and session_year

	context = {
		'courses':courses,
		'sessions':session_years
	}
	return render(request, 'student/add-student.html', context)


	''' NOTE about adding student as user as well as as student

		1. First thing first: fetch the course and session
		2. Add logic if there is request method of POST to process the form input
		3. Check the existance of email and username in the db bc they are unique
		   send messages if any of them is exists in the db
		4. Process the request if email and username are not exists in the db
		5. Making TWO in ONE: Student as user and Student's choice for course and session_year
	
	'''


# Add student end ----------------------------------------------------


def list_student(request):
	all_students = Student.objects.all() 
	context = {'students':all_students}
	return render(request, 'student/list-student.html', context)


def edit_student(request,id):
	student = Student.objects.filter(id=id)
	# Testing
	print(student)
	courses = Course.objects.all() 
	# Testing
	# print(courses)
	session_years = Session_Year.objects.all()
	# Tesing
	# print(session_years)

	context = {'student':student, 'courses':courses, 'sessions':session_years}
	return render(request, 'student/detail-student.html', context)

apps/student/templates/student/add-student.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Add Student {% endblock title %}

{% block content %}

        <div class="content container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <form 
                                method="POST" 
                                action="{% url 'student:add_student' %}"
                                enctype="multipart/form-data">

                                {% csrf_token %}

                                <div class="col-sm-12">
                                    <h5 class="form-title"><span>Add Student</span></h5>
                                </div>

                                {% include 'shared/flash-messages.html' %}

                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Profile Pic</label>
                                        <input 
                                            type="file" 
                                            name="profile_pic" 
                                            class="form-control"
                                            required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>First Name</label>
                                        <input 
                                            type="text" 
                                            name="first_name" 
                                            class="form-control"
                                            placeholder="Enter first name" 
                                            value="{{user.first_name}}" 
                                            required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Last Name</label>
                                        <input 
                                            type="text" 
                                            name="last_name" 
                                            class="form-control" 
                                            placeholder="Enter last name" 
                                            value="{{user.last_name}}" 
                                            required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                       <label>Gender</label>
                                       <select
                                            type="text" 
                                            name="gender" 
                                            class="form-control"
                                            required>
                                          <option>Select Gender</option>
                                          <option value="Female">Female</option>
                                          <option value="Male">Male</option>
                                          <option value="Others">Others</option>
                                       </select>
                                    </div>
                                 </div>

                                 <div class="col-sm-12">
                                    <div class="form-group">
                                       <label>Address</label>
                                       <textarea
                                            type="text" 
                                            name="address"
                                            required
                                            class="form-control"></textarea>
                                    </div>
                                 </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                       <label>Course</label>
                                       <select
                                            type="text" 
                                            name="course_id" 
                                            class="form-control"
                                            required>
                                          <option>Select Course</option>
                                          {% if courses %}
                                          {% for course in courses %}
                                          <option value="{{course.id}}">{{course.name}}</option>
                                          {% endfor %}
                                          {% else %}
                                          <p>No courses found</p>
                                          {% endif %}
                                       </select>
                                    </div>
                                 </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                       <label>Session Year</label>
                                       <select
                                            type="text" 
                                            name="session_year_id" 
                                            class="form-control"
                                            required>
                                          <option>Select Session Year</option>

                                          {% if sessions %}
                                          {% for session in sessions %}
                                          <option value="{{session.id}}">{{session.session_start}} to {{session.session_end}}</option>
                                          {% endfor %}
                                          {% else %}
                                          <p>No sessions found</p>
                                          {% endif %}
                                       </select>
                                    </div>
                                 </div>

                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input 
                                            type="text" 
                                            name="email" 
                                            class="form-control" 
                                            placeholder="Enter email"
                                            value="{{user.email}}"
                                            required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input 
                                            type="text" 
                                            name="username" 
                                            class="form-control" 
                                            placeholder="Enter username"
                                            value="{{user.username}}"
                                            required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input 
                                            type="password" 
                                            name="password" 
                                            class="form-control" 
                                            placeholder="" 
                                            value="" 
                                            required />
                                    </div>
                                </div>

                                <div class="col-12">
                                    <button 
                                        type="submit"
                                        class="btn btn-primary">Add Student</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}

apps/student/templates/student/detail-student.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Edit Student {% for i in student %}{{i.admin.first_name|title}}{% endfor %} {% endblock title %}

{% block content %}

        <div class="content container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="card">
                        <div class="card-body">
                            <form 
                                method="POST" 
                                action="{% url 'student:add_student' %}"
                                enctype="multipart/form-data">

                                {% csrf_token %}

                                <div class="col-sm-12">
                                    <h5 class="form-title"><span>Add Student</span></h5>
                                </div>

                                {% include 'shared/flash-messages.html' %}

                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Profile Pic</label>
                                        <input 
                                            type="file" 
                                            name="profile_pic" 
                                            class="form-control"
                                            required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>First Name</label>
                                        <input 
                                            type="text" 
                                            name="first_name" 
                                            class="form-control"
                                            placeholder="Enter first name" 
                                            value="{% for i in student %}{{i.admin.first_name|title}}{% endfor %}" 
                                            required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Last Name</label>
                                        <input 
                                            type="text" 
                                            name="last_name" 
                                            class="form-control" 
                                            placeholder="Enter last name" 
                                            value="{% for i in student %}{{i.admin.last_name|title}}{% endfor %}" 
                                            required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                       <label>Gender</label>
                                       <select
                                            type="text" 
                                            name="gender" 
                                            class="form-control"
                                            required>
                                          <option>Select Gender</option>
                                          {% for s in student %}
                                          <option value="{{student.gender}}">{{s.gender}}</option>
                                          {% endfor %}
                                       </select>
                                    </div>
                                 </div>

                                 <div class="col-sm-12">
                                    <div class="form-group">
                                       <label>Address</label>
                                       <textarea
                                            type="text" 
                                            name="address"
                                            required
                                            value=""
                                            class="form-control">{% for s in student %}{{s.address|title}}{% endfor %}</textarea>
                                    </div>
                                 </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                       <label>Course</label>
                                       <select
                                            type="text" 
                                            name="course_id" 
                                            class="form-control"
                                            required>
                                          <option>Select Course</option>
                                          {% if courses %}
                                          {% for course in courses %}
                                          <option value="{{course.id}}">{{course.name}}</option>
                                          {% endfor %}
                                          {% else %}
                                          <p>No courses found</p>
                                          {% endif %}
                                       </select>
                                    </div>
                                 </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                       <label>Session Year</label>
                                       <select
                                            type="text" 
                                            name="session_year_id" 
                                            class="form-control"
                                            required>
                                          <option>Select Session Year</option>

                                          {% if sessions %}
                                          {% for session in sessions %}
                                          <option value="{{session.id}}">{{session.session_start}} to {{session.session_end}}</option>
                                          {% endfor %}
                                          {% else %}
                                          <p>No sessions found</p>
                                          {% endif %}
                                       </select>
                                    </div>
                                 </div>

                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Email</label>
                                        <input 
                                            type="text" 
                                            name="email" 
                                            class="form-control" 
                                            placeholder="Enter email"
                                            value="{% for i in student %}{{i.admin.email}}{% endfor %}"
                                            required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Username</label>
                                        <input 
                                            type="text" 
                                            name="username" 
                                            class="form-control" 
                                            placeholder="Enter username"
                                            value="{% for i in student %}{{i.admin.username|title}}{% endfor %}"
                                            required />
                                    </div>
                                </div>
                                <div class="col-sm-12">
                                    <div class="form-group">
                                        <label>Password</label>
                                        <input 
                                            type="password" 
                                            name="password" 
                                            class="form-control" 
                                            placeholder="Fill only if you want to change your password"
                                            value="" 
                                            required />
                                    </div>
                                </div>

                                <div class="col-12">
                                    <button 
                                        type="submit"
                                        class="btn btn-primary">Update Student</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock content %}

apps/student/templates/student/list-student.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Student List {% endblock title %}

{% block content %}

         <div class="content container-fluid">
            <div class="page-header">
               <div class="row align-items-center">
                  <div class="col">
                     <h3 class="page-title">Students</h3>
                     <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Dashboard</a></li>
                        <li class="breadcrumb-item active">Students</li>
                     </ul>
                  </div>
                  <div class="col-auto text-right float-right ml-auto">
                     <a href="#" class="btn btn-outline-primary mr-2"><i class="fas fa-download"></i> Download</a>
                     <a href="add-student.html" class="btn btn-primary"><i class="fas fa-plus"></i></a>
                  </div>
               </div>
            </div>
            <div class="row">
               <div class="col-sm-12">
                  <div class="card card-table">
                     <div class="card-body">
                        <div class="table-responsive">
                           <table class="table table-hover table-center mb-0 datatable">
                              <thead>
                                 <tr>
                                    <th>ID</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Course</th>
                                    <th>Session year</th>
                                    <th>Gender</th>
                                    <th>Address</th>
                                    <th>Created</th>
                                    <th>Updated</th>
                                    <th class="text-right">Action</th>
                                 </tr>
                              </thead>
                              <tbody>

                              	<!-- Student list -->
                              	{% if students %}
                              	{% for student in students %}
                                 <tr>
                                    <td>{{student.id}}</td>
                                    <td>
                                       <h2 class="table-avatar">
                                          <a href="{% url 'student:edit_student' student.id %}" class="avatar avatar-sm mr-2"><img class="avatar-img rounded-circle" src="{{student.admin.profile_pic.url}}" alt="User Image"></a>
                                          <a href="{% url 'student:edit_student' student.id %}">{{student.admin.first_name}}&nbsp;{{student.admin.last_name}}</a>
                                       </h2>
                                    </td>
                                    <td>{{student.admin.email}}</td>
                                    <td>{{student.course_id.name}}</td>
                                    <td>{{student.session_year_id.session_start}} to {{student.session_year_id.session_end}}</td>
                                    <td>{{student.gender}}</td>
                                    <td>{{student.address}}</td>
                                    <td>{{student.created_at}}</td>
                                    <td>{{student.updated_at}}</td>
                                    <td class="text-right">
                                       <div class="actions">
                                          <a href="{% url 'student:edit_student' student.id %}" class="btn btn-sm bg-success-light mr-2">
                                          <i class="fas fa-pen"></i>
                                          </a>
                                          <a href="#" class="btn btn-sm bg-danger-light">
                                          <i class="fas fa-trash"></i>
                                          </a>
                                       </div>
                                    </td>
                                 </tr>
                                 {% endfor %}
                                 {% else %}
                                 <tr><td><p>No student found!</p></td></tr>
                                 {% endif %}
                                 <!-- Student list end-->
                              </tbody>
                           </table>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>

{% endblock content %}