apps/hod/urls.py
# apps/hod/urls.py

# Django modules
from django.urls import path

# Locals
from apps.hod import views 

app_name = 'hod'

urlpatterns = [

    path('hod/', views.hod_home, name='hod_home'),
    
]

apps/student/urls.py
# apps/student/urls.py

# Django modules
from django.urls import path

# Locals
from apps.student import views 

app_name = 'student'

urlpatterns = [

    path('student/add-student/', views.add_student, name='add_student'),
    path('student/list/', views.list_student, name='list_student'),
    path('student/edit/<str:id>/', views.edit_student, name='edit_student'),
    
]

apps/user/urls.py
# apps/user/urls.py

# Django modules
from django.urls import path

# Locals
from apps.user import views 

app_name = 'user'

urlpatterns = [

    # Login template
    path('', views.user_login, name='user_login'),
    # User login
    path('doLogin/', views.doLogin, name='doLogin'),
    # User logout
    path('doLogout/', views.doLogout, name='doLogout'),
    # User profile
    path('profile/', views.profile, name='profile'),
    # User profile
    path('profile/update/', views.profile_update, name='profile_update'),
]

config/urls.py
# config/urls.py

# Django modules
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    # user
    path('', include('apps.user.urls', namespace='user')),

    # hod
    path('', include('apps.hod.urls', namespace='hod')),


    # student
    path('', include('apps.student.urls', namespace='student')),


    # main
    path('', include('apps.main.urls', namespace='main')),

    # Admin
    path('admin/', admin.site.urls),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/shared/flash-messages.html
                                <!-- Falsh Message -->
                                {% if messages %}
                                {% for message in messages %}
                                {% if message.tags == 'error' %}
                                <div class="alert alert-danger alert-dismissible fade show" role="alert">
                                  {{message}}
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                <!-- Flash message end -->

                                <!-- Falsh Message -->
                                {% if messages %}
                                {% for message in messages %}
                                {% if message.tags == 'success' %}
                                <div class="alert alert-success alert-dismissible fade show" role="alert">
                                  {{message}}
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                <!-- Flash message end -->

                                <!-- Falsh Message -->
                                {% if messages %}
                                {% for message in messages %}
                                {% if message.tags == 'warning' %}
                                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                  {{message}}
                                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                  </button>
                                </div>
                                {% endif %}
                                {% endfor %}
                                {% endif %}
                                <!-- Flash message end -->

templates/shared/footer.html
{% load static %}

            <footer>
                <p>Copyright © 2020 Dreamguys.</p>
            </footer>
        </div>

templates/shared/head.html
{% load static %}

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0" />
    <link rel="shortcut icon" href="{% static 'assets/img/favicon.png' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,500;0,600;0,700;1,400&amp;display=swap" />
    <link rel="stylesheet" href="{% static 'assets/plugins/bootstrap/css/bootstrap.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/fontawesome.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/plugins/fontawesome/css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" />

templates/shared/header.html
{% load static %}

        <div class="header">
            <div class="header-left">
                <a href="index.html" class="logo">
                    <img src="{% static 'assets/img/logo.png' %}" alt="Logo" />
                </a>
                <a href="index.html" class="logo logo-small">
                    <img src="{% static 'assets/img/logo-small.png' %}" alt="Logo" width="30" height="30" />
                </a>
            </div>
            <a href="javascript:void(0);" id="toggle_btn">
                <i class="fas fa-align-left"></i>
            </a>
            <div class="top-nav-search mt-3">
                <!-- <form>
                    <input type="text" class="form-control" placeholder="Search here" />
                    <button class="btn" type="submit"><i class="fas fa-search"></i></button>
                </form> -->
                <h4><strong>Welcome</strong>&nbsp;<span>{{user.first_name|title}}&nbsp;{{user.last_name|title}}</span></h4>
            </div>
            <a class="mobile_btn" id="mobile_btn">
                <i class="fas fa-bars"></i>
            </a>
            <ul class="nav user-menu">
                <li class="nav-item dropdown noti-dropdown">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown"> <i class="far fa-bell"></i> <span class="badge badge-pill">3</span> </a>
                    <div class="dropdown-menu notifications">
                        <div class="topnav-dropdown-header">
                            <span class="notification-title">Notifications</span>
                            <a href="javascript:void(0)" class="clear-noti"> Clear All </a>
                        </div>
                        <div class="noti-content">
                            <ul class="notification-list">
                                <li class="notification-message">
                                    <a href="#">
                                        <div class="media">
                                            <span class="avatar avatar-sm">
                                                <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-02.jpg' %}" />
                                            </span>
                                            <div class="media-body">
                                                <p class="noti-details"><span class="noti-title">Carlson Tech</span> has approved <span class="noti-title">your estimate</span></p>
                                                <p class="noti-time"><span class="notification-time">4 mins ago</span></p>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li class="notification-message">
                                    <a href="#">
                                        <div class="media">
                                            <span class="avatar avatar-sm">
                                                <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-11.jpg' %}" />
                                            </span>
                                            <div class="media-body">
                                                <p class="noti-details"><span class="noti-title">International Software Inc</span> has sent you a invoice in the amount of <span class="noti-title">$218</span></p>
                                                <p class="noti-time"><span class="notification-time">6 mins ago</span></p>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li class="notification-message">
                                    <a href="#">
                                        <div class="media">
                                            <span class="avatar avatar-sm">
                                                <img class="avatar-img rounded-circle" alt="User Image" src="{% static 'assets/img/profiles/avatar-17.jpg' %}" />
                                            </span>
                                            <div class="media-body">
                                                <p class="noti-details"><span class="noti-title">John Hendry</span> sent a cancellation request <span class="noti-title">Apple iPhone XR</span></p>
                                                <p class="noti-time"><span class="notification-time">8 mins ago</span></p>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                                <li class="notification-message">
                                    <a href="#">
                                        <div class="media">
                                            <span class="avatar avatar-sm">
                                                <img 
                                                    class="avatar-img rounded-circle" 
                                                    alt="User Image" 
                                                    src="{% static 'assets/img/profiles/avatar-13.jpg' %}" />
                                            </span>
                                            <div class="media-body">
                                                <p class="noti-details"><span class="noti-title">Mercury Software Inc</span> added a new product <span class="noti-title">Apple MacBook Pro</span></p>
                                                <p class="noti-time"><span class="notification-time">12 mins ago</span></p>
                                            </div>
                                        </div>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="topnav-dropdown-footer">
                            <a href="#">View all Notifications</a>
                        </div>
                    </div>
                </li>
                <li class="nav-item dropdown has-arrow">
                    <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                        <span class="user-img">
                            {% if user.profile_pic %}
                            <img 
                            class="rounded-circle" 
                            src="{{user.profile_pic.url}}" 
                            width="31" alt="User profile pic." /></span>
                            {% else %}
                            <img 
                            class="rounded-circle" 
                            src="{% static 'assets/img/profiles/default-profile.png' %}" 
                            width="31" alt="User profile pic." /></span>
                            {% endif %}
                    </a>
                    <div class="dropdown-menu">
                        <div class="user-header">
                            <div class="avatar avatar-sm">

                                {% if user.profile_pic %}
                                <img 
                                class="rounded-circle" 
                                src="{{user.profile_pic.url}}" 
                                width="31" alt="User profile pic." /></span>
                                {% else %}
                                <img 
                                class="rounded-circle" 
                                src="{% static 'assets/img/profiles/default-profile.png' %}" 
                                width="31" alt="User profile pic." /></span>
                                {% endif %}
                                
                            </div>
                            <div class="user-text">
                                <h6>{{user.first_name|title}}&nbsp;{{user.last_name|title}}</h6>
                                {% if user.user_type == '1' %}
                                <p class="text-muted mb-0">HOD</p>
                                {% elif user.user_type == '2' %}
                                <p class="text-muted mb-0">Staff</p>
                                {% elif user.user_type == '3' %}
                                <p class="text-muted mb-0">Student</p>
                                {% else %}
                                <p class="text-muted mb-0">No user type found!</p>
                                {% endif %}
                            </div>
                        </div>
                        <a class="dropdown-item" href="{% url 'user:profile' %}">Profile update</a>
                        <a class="dropdown-item" href="inbox.html">Inbox</a>
                        <a class="dropdown-item" href="{% url 'user:doLogout' %}">Logout</a>
                    </div>
                </li>
            </ul>
        </div>

templates/shared/scripts.html
{% load static %}

    <script src="{% static 'assets/js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'assets/js/popper.min.js' %}"></script>
    <script src="{% static 'assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/plugins/slimscroll/jquery.slimscroll.min.js' %}"></script>
    <script src="{% static 'assets/plugins/apexchart/apexcharts.min.js' %}"></script>
    <script src="{% static 'assets/plugins/apexchart/chart-data.js' %}"></script>
    <script src="{% static 'assets/js/script.js' %}"></script>

templates/shared/sidebar.html
{% load static %}

        <div class="page-wrapper">

            <div class="sidebar" id="sidebar">
                <div class="sidebar-inner slimscroll">
                    <div id="sidebar-menu" class="sidebar-menu">
                        <ul>
                            <li class="menu-title">
                                <span>Main Menu</span>
                            </li>

                            <li>
                                <a href="{% url 'hod:hod_home' %}"><i class="fas fa-holly-berry"></i> <span>Dashboard</span></a>
                            </li>

                            <li class="submenu">
                                <a href="#"><i class="fas fa-user-graduate"></i> <span> Students</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li><a href="{% url 'student:add_student' %}">Add Student </a></li>
                                    <li><a href="{% url 'student:list_student' %}">View Student </a></li>
                                    
                                </ul>
                            </li>

                            <li class="submenu">
                                <a href="#"><i class="fas fa-chalkboard-teacher"></i> <span> Staff</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <!-- <li><a href="teachers.html">Staff List</a></li> -->
                                    <li><a href="teacher-details.html">Staff View</a></li>
                                    <li><a href="add-teacher.html">Staff Add</a></li>
                                    <li><a href="edit-teacher.html">Staff Edit</a></li>
                                </ul>
                            </li>
                            
                            <li class="submenu">
                                <a href="#"><i class="fa fa-graduation-cap"></i> <span> Courses</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li><a href="departments.html">Course View</a></li>
                                    <li><a href="add-department.html">Course Add</a></li>
                                    <li><a href="edit-department.html">Course Edit</a></li>
                                </ul>
                            </li>

                           <li class="submenu">
                                <a href="#"><i class="fas fa-book-reader"></i> <span> Subjects</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li><a href="subjects.html">Subject List</a></li>
                                    <li><a href="add-subject.html">Subject Add</a></li>
                                    <li><a href="edit-subject.html">Subject Edit</a></li>
                                </ul>
                            </li>

                           <li class="submenu">
                                <a href="#"><i class="fas fa-clock"></i> <span> Session</span> <span class="menu-arrow"></span></a>
                                <ul>
                                    <li><a href="subjects.html">Session View</a></li>
                                    <li><a href="add-subject.html">Session Add</a></li>
                                    <li><a href="edit-subject.html">Session Edit</a></li>
                                </ul>
                            </li>

                            <li>
                                <a href="holiday.html"><i class="fa fa-calendar"></i> <span>Attendance</span></a>
                            </li>

                            <li>
                                <a href="holiday.html"><i class="fas fa-comments"></i> <span>Staff Feedback</span></a>
                            </li>

                            <li>
                                <a href="holiday.html"><i class="fas fa-comments"></i> <span>Student Feedback</span></a>
                            </li>

                            <li>
                                <a href="holiday.html"><i class="fas fa-envelope"></i> <span>Staff Leave</span></a>
                            </li>

                            <li>
                                <a href="holiday.html"><i class="fas fa-envelope"></i> <span>Student Leave</span></a>
                            </li>

                            <li>
                                <a href="{% url 'user:doLogout' %}"><i class="fas fa-sign-out-alt"></i> <span>Logout</span></a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>